### ISSUE TITLE
Integration with Kadu

### ISSUE THREAD

**Issue by BartekSz** [screenfreeze/messagingmenu#23]
Welcome.
I have question for you. It is possible to do integration with Kadu (Polish multicomunicator)?

**Comment by BartekSz** [comment]
Hi. I create for you file with polish language. You can download it from my Dropbox (if you want of course):
https://www.dropbox.com/s/kaese6a6ethc87t/pl.po?dl=0

**Comment by sinisterstuf** [comment]
Fantastic, I commited your translation file 8d616715ce4a8ebdd230b2313a18bda638f585cd, thanks a lot! In the file I changed 2 lines: `Language: pl\n` (it was `de`) and the `Plural-Forms` for Polish, it looks like they're quite complicated: `nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n` which I copied from [here](http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html).

What name did you have to add to the list to get Kadu working? `kadu`? `Kadu`? etc?

**Comment by sinisterstuf** [comment]
OK, I installed Kadu just to check this out and it needs to be listed as `kadu`.
