### ISSUE TITLE
Add support for gnome Fractal

### ISSUE THREAD

**Issue by db0x** [screenfreeze/messagingmenu#44]
Please add support for gnome Fractal (matrix-client) 

https://wiki.gnome.org/Apps/Fractal

**Comment by sinisterstuf** [comment]
I've added `org.gnome.Fractal` to the list of compatible chats based on the .desktop file I found in the Fractal package for Arch Linux. :ok_hand: This'll go out with the next release of the plugin, but if you want, you can test it beforehand if you install the plugin manually.
