### ISSUE TITLE
Does not work with gnome 3.32

### ISSUE THREAD

**Issue by ChrisLauinger77** [screenfreeze/messagingmenu#45]
After update to gnome 3.32 the extension shows error on extensions.gnome.org
![ext](https://user-images.githubusercontent.com/3518684/55274543-cb145900-52d9-11e9-8bff-9d8f3feee387.png)

**Comment by tledford4** [comment]
Also observed in latest Stable Manjaro Gnome update (error button).  If enabled on my machine with Gnome 3.32, causes gnome-shell to segfault with libsoup.

**Comment by grizzlysmit** [comment]
is this still being developed ?? I loved this extension

**Comment by sinisterstuf** [comment]
@grizzlysmit not actively, it's receiving fixes and compatibility updates but they're hard for me to reproduce since I stopped using Gnome.

@ChrisLauinger77 @tledford4 if this is reproducible, could you please provide any log or stack trace to help find the source of the error so that we can fix it in the code?

**Comment by ChrisLauinger77** [comment]
in lookinglass is see this:
![Bildschirmfoto von 2019-08-22 15-04-36](https://user-images.githubusercontent.com/3518684/63517005-6a86f200-c4ee-11e9-8be3-452ccdb1d8db.png)

**Comment by sinisterstuf** [comment]
Great, there are no occurrences of that in the code, I guess that's exactly the problem. I suppose something in the way GNOME Shell allows javascript extensions to interact with it has changed except I haven't been paying attention to changes. Does anyone have documentation or changelog for GNOME Shell at hand? Otherwise I guess I'll look for it later.

**Comment by ChrisLauinger77** [comment]
I think here is something intresting:
https://github.com/zhanghai/gnome-shell-extension-es6-class-codemod

**Comment by sinisterstuf** [comment]
OK, a quick Google search found this documentation linked to from an issue in a different extension: https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/HACKING.md#classes

The comment that linked there was this one for context: https://gitlab.gnome.org/GNOME/gjs/issues/233

**Comment by sinisterstuf** [comment]
Ah, thanks for the link, that looks perfect! Could you try running that on this code and submitting a pull request with the result? 🙏

**Comment by ChrisLauinger77** [comment]
Will do

**Comment by ChrisLauinger77** [comment]
It askes 2 questions:
Is PopupMenu.PopupBaseMenuItem a GObject class? (y/n): n
Is PanelMenu.Button a GObject class? (y/n): n

I answered both with no.
Now I get in log:
Aug 22 15:49:12 debian gnome-software[2495]: messagingmenu_screenfreeze.net has error: TypeError: this._getApps is not a function

**Comment by tledford4** [comment]
When I added my note to this ticket on April 1st, I was able to install the extension, it is just that if enabled, it crashed gnome-shell with a segfault in a library.  However, now it won't install (I had uninstalled it), I get the same "this._construct is not a function" error that Chris mentions above.

This is on up-to-date Manjaro (stable) gnome.

**Comment by ChrisLauinger77** [comment]
made the pull request after conversion with jscodeshift - maybe you have a clue why its still nagging ?

**Comment by sinisterstuf** [comment]
Thanks for the pull request #46, I left you a comment there. It seems the converter has fixed all (or most) of the function definitions but missed some of the function calls. I'll have access to a computer running GNOME when I get back to work on Monday, but until then if you want you can try fiddling about with different ways of calling the renamed/modified functions 🙂

**Comment by ChrisLauinger77** [comment]
You are welcome. I try fiddling tomorrow. Not really know javascript very well to be honest but try to dig in.

**Comment by ChrisLauinger77** [comment]
I converted one more time but with
Is PopupMenu.PopupBaseMenuItem a GObject class? (y/n): n
Is PanelMenu.Button a GObject class? (y/n): y

Now the extension loads :) It does not show an icon though ;(
![Bildschirmfoto von 2019-09-01 11-30-22](https://user-images.githubusercontent.com/3518684/64074470-f1d12400-ccab-11e9-9ee4-a929c2ed22f7.png)

**Comment by ChrisLauinger77** [comment]
I changed the icon to mail-message-new-symbolic.
This is how it looks now:
![Bildschirmfoto von 2019-09-01 14-42-27](https://user-images.githubusercontent.com/3518684/64076573-cc054880-ccc6-11e9-9614-4f8202adec02.png)

**Comment by tledford4** [comment]
Looks great to me, Chris!  Look forward to trying it after you've checked it in, which I assume you'll do when you're comfortable with that.

**Comment by ChrisLauinger77** [comment]
It is checked in @tledford4. But into my fork of the repo. 
I also made a pull request from my fork to this repo. You can find it under pull requests. 
Only @sinisterstuf can close the pull request and update this repo though.

**Comment by tledford4** [comment]
Thank you, Chris, working just fine on Manjaro Stable (up to date) running version 3.32.2 of gnome shell.  Nice to have it back, appreciate your work on it!

**Comment by ChrisLauinger77** [comment]
I figured the compose and contacts button did not work after conversion to ES6.
Just checked in the fix for that.
